### ISSUE TITLE
Permalinks for specific build configurations

### ISSUE THREAD

**Issue by mathiasbynens** [Modernizr/the-old-modernizr.com#1]
Currently the header of a generated Modernizr build looks something like this (note the _Contains_ section):

``` js
/* Modernizr 2.0.6 (Custom Build) | MIT & BSD
 * Contains: fontface | backgroundsize | borderimage | borderradius | boxshadow | flexbox | multiplebgs | opacity | rgba | textshadow | cssanimations | csscolumns | generatedcontent | cssgradients | cssreflections | csstransforms | csstransforms3d | csstransitions | iepp | cssclasses | teststyles | testprop | testallprops | prefixes | domprefixes | load
 */
```

It would be cool if there was a permalink to the builder with these settings predefined. This would make updating to a more recent Modernizr version a breeze, even with custom builds.

For the above configuration, this URL could be used:

```
http://www.modernizr.com/download/#fontface-backgroundsize-borderimage-borderradius-boxshadow-flexbox-multiplebgs-opacity-rgba-textshadow-cssanimations-csscolumns-generatedcontent-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-iepp-cssclasses-teststyles-testprop-testallprops-prefixes-domprefixes-load
```

You could consider replacing the `Contains:` paragraph with this link, since it basically gives the same information, and much more.

**Comment by mathiasbynens** [comment]
Oh wait… You guys already do this nowadays on http://www.modernizr.com/download/. The project I was working on just happened to use an older 2.0.6 build that didn’t have such a link.

#facepalm

Related commit: c6132da0b9cd2fdeb0b7875176a17392405c03e1

**Comment by paulirish** [comment]
:p
