### ISSUE TITLE
Make the menu fixed

### ISSUE THREAD

**Issue by lyrixx** [Modernizr/the-old-modernizr.com#11]
Hello.

First : Thanks you for your nice libs ;)

Second :  Can you "fixed" (with css/js)  the menu when we scroll on this page : http://modernizr.com/docs/ . Thanks to this patch, we can always see the menu and access other section very quickly ?

Thanks.

**Comment by lyrixx** [comment]
ping ?

**Comment by KuraFire** [comment]
What's the patch?

**Comment by lyrixx** [comment]
Oups. ;)

## I did not write any patch. I hope you could do it

Pineau Grégoire http://gregoirepineau.fr/

2012/8/8 Faruk Ateş notifications@github.com

**Comment by KuraFire** [comment]
We'll consider it for the next major change to the site. It may (heavily) conflict with some of our plans though, so we'll see.

**Comment by lyrixx** [comment]
ok, thanks.
