### ISSUE TITLE
Strange "squares" on website footer (section used by) with Firefox

### ISSUE THREAD

**Issue by moretti** [Modernizr/the-old-modernizr.com#12]
Please, take a look at <a href="http://i.imgur.com/h9Si2.png">this</a> screenshot.
I'm using Firefox 12 on Windows7 x64.

**Comment by ghost** [comment]
The easiest way to solve this problem is by adding "color: transparent;" at line 861 (selectors: "# used-by ol, # used-by ol li").
This site needs an urgent review of the css code! I found another bug in IE8 and I'm opening a new issue!

**Comment by bobthecow** [comment]
This is most likely because the special "ç" font is missing a space character. @KuraFire is looking into this issue elsewhere, and will prolly be able to shed some light on the matter.

**Comment by KuraFire** [comment]
@moretti Is the issue fixed or do you still see this in your Firefox on Windows? I don't see it in Firefox/Mac anymore, where it used to occasionally appear.

**Comment by moretti** [comment]
@KuraFire I don't see it either in Firefox/Windows. I guess we can close the issue then.

**Comment by KuraFire** [comment]
@moretti Thanks!
