### ISSUE TITLE
cannot toggle extensibility and community addons

### ISSUE THREAD

**Issue by anselmh** [Modernizr/the-old-modernizr.com#2]
I cannot toggle (better: open) the closed extensibility and community addons sections in Google Chrome (18.0.x). Works in other browsers without problems.

**Comment by paulirish** [comment]
we have a fix ready for this in less than 24hrs

On Mon, Feb 6, 2012 at 12:11 AM, Anselm Hannemann <
reply@reply.github.com

**Comment by anselmh** [comment]
great! is this the release date of 2.5? ;)

**Comment by paulirish** [comment]
yeah.

**Comment by paulirish** [comment]
try now. :)

**Comment by anselmh** [comment]
Yay!
