### ISSUE TITLE
Detecting Opera 12.5 transition end possible w/ the prefixed method? [Docs question]

### ISSUE THREAD

**Issue by alexisgo** [Modernizr/the-old-modernizr.com#24]
Hi ya'll,

This is likely a question for Opera, and I will ask them as well, but wanted to get your take.

I've been using your incredibly helpful code snippet from the docs section on the prefixed method (http://modernizr.com/docs/#prefixed) that details how to use it to ascertain which transition end event to bind to.

The site provides this code: 

``` js
var transEndEventNames = {
    'WebkitTransition' : 'webkitTransitionEnd',
    'MozTransition'    : 'transitionend',
    'OTransition'      : 'oTransitionEnd',
    'msTransition'     : 'MSTransitionEnd',
    'transition'       : 'transitionend'
},
transEndEventName = transEndEventNames[ Modernizr.prefixed('transition') ];
```

Per Ian Lunn at http://www.ianlunn.co.uk/blog/articles/opera-12-otransitionend-bugs-and-workarounds/ in Opera 12 they changed the case of oTransitionEnd to be otransitionend instead. So I modified the Opera line to:
     'OTransition'      : 'oTransitionEnd otransitionend',

This works in Opera 12 just fine, but in Opera 12.5, I noticed that Modernizr.prefixed('transition') actually returns... WebkitTransition. I'm assuming that's due to their choice to support the -webkit- prefixes, but I don't understand why WebkitTransition is returned prior to the Opera version.

Now, I realize this isn't a Modernizr problem, but an Opera one, but I was hoping you might update the docs and the code snippet to give me a hint as to how to best accomodate Opera 11, 12, and well, 12.5.

**Comment by paulirish** [comment]
Opera supports webkit prefixes as of 12.5 yes.

that's their choice but this behavior is up to them. it reports webkit first because our `for` loop to check all prefixes checks webkit first.

soo... this shouldn't be a problem for you.. it's just the way it is. :)
