### ISSUE TITLE
Broken link on resources page

### ISSUE THREAD

**Issue by jrsconfitto** [Modernizr/the-old-modernizr.com#27]
The respondjs link takes me somewhere with a 403 forbidden :( - [Resources Line 39](https://github.com/Modernizr/modernizr.com/blob/gh-pages/resources/index.html#L39)

**Comment by alrra** [comment]
It seems they don't "like" the `Referer` header:

`curl -IsS -H "Referer: http://www.example.com" http://filamentgroup.com/lab/respondjs_fast_css3_media_queries_for_internet_explorer_6_8_and_more/`

HTTP/1.1 403 Forbidden

`curl -IsS http://filamentgroup.com/lab/respondjs_fast_css3_media_queries_for_internet_explorer_6_8_and_more/`

HTTP/1.1 200 OK

@paulirish maybe change the URL to https://github.com/scottjehl/Respond ? (uses will end up there anyway) 

(Cc: @scottjehl)

**Comment by KuraFire** [comment]
Done. Thanks for noticing & reporting! :+1:
