### ISSUE TITLE
yepnope is included in custom build when unchecked in builder

### ISSUE THREAD

**Issue by zachleat** [Modernizr/the-old-modernizr.com#31]
To Reproduce:
1. Go to http://modernizr.com/download/
2. Uncheck Modernizr.load (yepnope.js)
3. Click the Download Custom build button.
4. Pour water on the build gremlin

Unfortunately yepnope is still in the JavaScript.

PS: I still love yepnope.

**Comment by stucox** [comment]
Are you sure yepnope's still in there?

This is the build I got from following your instructions: https://gist.github.com/stucox/9fbd6a7c789c0f110397 — I can't see any sign of yepnope in there.

**Comment by zachleat** [comment]
Oh, sorry. I misstated the reproduction steps:
1. Go to http://modernizr.com/
2. Click the DEVELOPMENT download button.
3. Continue from step 2 in original post.

https://gist.github.com/zachleat/5405752

**Comment by stucox** [comment]
Ok cheers. We're rewriting the builder for v3, so hopefully this bug will magically go away... but we'll leave this ticket open so we remember to check ;-)

**Comment by zachleat** [comment]
Thanks!

**Comment by patrickkettner** [comment]
fixed! when the new site was released
