### ISSUE TITLE
Download Builder irritation in Mozilla Firefox

### ISSUE THREAD

**Issue by homeworkprod** [Modernizr/the-old-modernizr.com#42]
I lost a serious amount of time and nerves by missing that the "Extensibility" [1] and "Non-core detects" [2] areas are actually expandable headlines.

See this screenshot:
<a href="http://imgur.com/t7lRhOb"><img src="http://i.imgur.com/t7lRhOb.png" title="Hosted by imgur.com" /></a>

**Issue 1:** They have a dark background and a border, and thus look different than the other checkbox list blocks' headlines (lighter background, no border) [3].

**Issue 2:** They don't look like they'd be expendable – in Firefox (seen in Firefox 27 and Iceweasel 24.2). The each have a triangle in front of them in other browsers (seen in Chromium 32), though.

While I am in favor of using HTML5 wherever it makes sense, the interactive `<details>` and `<summary>` elements are either not properly styled (though I've come across a `-moz-`-prefixed CSS attribute there) or just nor ready to be used today. Especially not on the website of a product that aims to unify web browser rendering and behaviour.

Please either fix the styling or avoid those elements for now.

**Comment by patrickkettner** [comment]
Hey @homeworkprod - super sorry you had problems. We are in the midst of a complete redesign, so this problem should disappear soon. I will try and update the existing one even sooner though - thanks again for opening the issue!

**Comment by homeworkprod** [comment]
Thanks.

**Comment by stucox** [comment]
@homeworkprod Can you confirm you can see arrows now?

**Comment by homeworkprod** [comment]
Yes, this fixes the second issue I described above – thanks.

Regarding the first issue: Please consider unifying the checkbox groups' looks as part of your redesign as well.
