### ISSUE TITLE
Add a little explanation in the readme

### ISSUE THREAD

**Issue by robwierzbowski** [Modernizr/the-old-modernizr.com#45]
I'm having a hard time figuring out what options and tests are what in the V3 branch, which makes it hard to build modernizr to test/use new features. Are certain options necessary for a working build? What's the difference between testPropsAll and the testAllProps option? Etc, etc.

I know this is a work in progress, so consider this issue low priority. I do like some of the new feature tests of V3, so if a little readme love would help me get to a working build I'd certainly appreciate it.

**Comment by patrickkettner** [comment]
what features are you referring to?

the default `grunt` should build all tests.

**Comment by robwierzbowski** [comment]
> what features are you referring to?

What if I want to make a custom build? Maybe using the grunt plugin with a hand edited config-all.json would be a better idea.

**Comment by patrickkettner** [comment]
depends on what you want to make custom :]

but you would just remove what you don't want from [lib/config-all.json](https://github.com/Modernizr/Modernizr/blob/master/lib/config-all.json).

I would be hesitant adding any of this information to the readme, since the preffered way of doing this would be using the grunt plugin.

Also, was there a reason this was opened on the .com, rather than the main repo?

cheers!

**Comment by robwierzbowski** [comment]
> Also, was there a reason this was opened on the .com, rather than the main repo?

I wanted to build a pre-release using something closer to what the other maintainers of the project I work on will use, but it's not a big deal.

> I would be hesitant adding any of this information to the readme, since the preffered way of doing this would be using the grunt plugin.

Yep, no problem. Closing.

**Comment by stucox** [comment]
@robwierzbowski btw the [v3.modernizr.com repo](https://github.com/Modernizr/v3.modernizr.com) is where we’ve been doing most of our work ready for the v3 beta – in particular, see my [v3pre-downloader branch](https://github.com/Modernizr/v3.modernizr.com/tree/v3pre-downloader), although it’s very much in a state of flux (aka trying to kick the thing out the door!)

The whole site’s currently undergoing a complete redesign & rewrite – although the mechanics of the builder will remain similar.
