### ISSUE TITLE
Sudden 404 issue

### ISSUE THREAD

**Issue by aish1550** [Modernizr/the-old-modernizr.com#55]
I understand there has been a new release for modernizr 3, which is fantastic, However, could this be linked to the following error on my console log when building with grunt? This has only been noticed yesterday. 

404 modernizr-latest.js

> > Generating a custom Modernizr build
> > Uglifying
> > 
> > Wrote file to dist/scripts/vendor/modernizr.js
> > The following tests could not be downloaded
> > 
> > ```
> > 404 http://modernizr.com/downloads/modernizr-latest.js
> > 
> > Check the Modulizr API for more info:
> > https://github.com/Modernizr/modernizr.com/blob/gh-pages/i/js/modulizr.js#L15-157
> > ```

**Comment by BaronSosaa** [comment]
Same problem here with other test.

Downloading source files
404 html5shiv-printshiv-3.6.js
404 modernizr.load.1.5.4.js
404 modernizr-latest.js

> > Generating a custom Modernizr build
> > Uglifying
> > 
> > Wrote file to src/Ento/WebsiteBundle/Resources/public/.temp/js/modernizr-custom.js
> > The following tests could not be downloaded
> > 
> > ```
> > 404 http://modernizr.com/i/js/html5shiv-printshiv-3.6.js
> > 404 http://modernizr.com/i/js/modernizr.load.1.5.4.js
> > 404 http://modernizr.com/downloads/modernizr-latest.js
> > 
> > Check the Modulizr API for more info:
> > https://github.com/Modernizr/modernizr.com/blob/gh-pages/i/js/modulizr.js#L15-157
> > ```

**Comment by patrickkettner** [comment]
hey guys!

thanks for the heads up.
this is an issue with the grunt plugin. closing in favor of the existing issue https://github.com/Modernizr/grunt-modernizr/issues/118

**Comment by aish1550** [comment]
Thanks @patrickkettner massively for the fix.
