### ISSUE TITLE
Decrease header font size in v3 redesign

### ISSUE THREAD

**Issue by hlfcoding** [Modernizr/the-old-modernizr.com#56]
It's comically big. See [blog section](https://modernizr.com/news).

**Comment by patrickkettner** [comment]
Hey there!

This is actually the wrong repo (modernizr-neue is the new site). We are iterating the design already over there, so I'm going to close this out in favor of it.

Cheers

**Comment by hlfcoding** [comment]
:+1: Please consider in your iterations.
