### ISSUE TITLE
Download page gives different Grunt options than current grunt-modernizr accepts

### ISSUE THREAD

**Issue by russelporosky** [Modernizr/the-old-modernizr.com#57]
The download page grunt config appears to deliver the v0.x compatible configuration object for grunt-modernizr, but now that v1.0.x is released, those options are very different.

In particular, and most maddening, the old `outputFile` being shown on the download page no longer has any effect. The new config uses `dest` instead (https://github.com/doctyper/customizr#config-file).

As it stands, if I `npm install grunt-modernizr --save-dev`, then go to the build page at https://modernizr.com/download/ and set my base options, then ask for the Grunt Config, that configuration will not work with substantial, un-noted editing.

**Comment by patrickkettner** [comment]
@metaloha this data is coming form [here](https://github.com/Modernizr/modernizr-neue/blob/83b0490563243ed22435690449b7cb84252b0158/frontend/js/download/util.js)

would you be interested in creating a PR to fix this?

**Comment by rejas** [comment]
Closing since this repo will be put in archive-mode
