### ISSUE TITLE
Display CSS Class/JS property name in brower feature search

### ISSUE THREAD

**Issue by philly385** [Modernizr/the-old-modernizr.com#58]
It would be nice to get the property names for the features when searching one in the global search (https://modernizr.com/download?setclasses). Working with the documentation is a little bit clumsy, it would be easier to get the prop name as additional info to the documentation and specification of the test.

**Comment by joecritch** [comment]
Hey, I've referenced this over on the correct repo for the site. https://github.com/Modernizr/modernizr-neue/issues/66. Closing this to avoid confusion.

**Comment by philly385** [comment]
Hey, sorry I didn't know this was the wrong repo. Thanks for moving it. Also thank you for the implementation, this was my first issue :)
